### ISSUE TITLE
What should I do if I want to support platform=win32 arch=ia32

### ISSUE THREAD

**Issue by RayCssjmt** [SnosMe/uiohook-napi#25] opened 2022-10-20 07:02 UTC
What should I do if I want to support platform=win32 arch=ia32

**Comment by SnosMe** [comment] 2022-10-20 11:00
I don't want to add binaries for legacy architecture. (Duplicate of #11)

However it works, all you need is vs build tools and it npm will compile it at the time package of installation.

https://github.com/nodejs/node-gyp#on-windows

**Closed by SnosMe** 2022-10-20 11:00 UTC
